package com.android.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.android.db.DesignationData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DESIGNATION_DATA.
*/
public class DesignationDataDao extends AbstractDao<DesignationData, Void> {

    public static final String TABLENAME = "DESIGNATION_DATA";

    /**
     * Properties of entity DesignationData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Designation = new Property(0, String.class, "Designation", false, "DESIGNATION");
    };


    public DesignationDataDao(DaoConfig config) {
        super(config);
    }
    
    public DesignationDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DESIGNATION_DATA' (" + //
                "'DESIGNATION' TEXT);"); // 0: Designation
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DESIGNATION_DATA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DesignationData entity) {
        stmt.clearBindings();
 
        String Designation = entity.getDesignation();
        if (Designation != null) {
            stmt.bindString(1, Designation);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public DesignationData readEntity(Cursor cursor, int offset) {
        DesignationData entity = new DesignationData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // Designation
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DesignationData entity, int offset) {
        entity.setDesignation(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(DesignationData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(DesignationData entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
