package com.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GAURD_MASTER.
 */
public class GaurdMaster {

    private String user_id;
    private String company_id;
    private String first_name;
    private String last_name;
    private String father_name;
    private String dob;
    private String age;
    private String phone;
    private String mobile;
    private String l_address;
    private String p_address;
    private String latitude;
    private String longitude;
    private String zip;
    private String user_name;
    private String password;
    private String email;
    private String status;
    private String is_deleted;
    private String created_by;
    private java.util.Date created_date;
    private String qr_code;
    private String session_token;
    private String apns_token;
    private String img_url;
    private String company_name;
    private String site_ids;
    private String designation;

    public GaurdMaster() {
    }

    public GaurdMaster(String user_id) {
        this.user_id = user_id;
    }

    public GaurdMaster(String user_id, String company_id, String first_name, String last_name, String father_name, String dob, String age, String phone, String mobile, String l_address, String p_address, String latitude, String longitude, String zip, String user_name, String password, String email, String status, String is_deleted, String created_by, java.util.Date created_date, String qr_code, String session_token, String apns_token, String img_url, String company_name, String site_ids, String designation) {
        this.user_id = user_id;
        this.company_id = company_id;
        this.first_name = first_name;
        this.last_name = last_name;
        this.father_name = father_name;
        this.dob = dob;
        this.age = age;
        this.phone = phone;
        this.mobile = mobile;
        this.l_address = l_address;
        this.p_address = p_address;
        this.latitude = latitude;
        this.longitude = longitude;
        this.zip = zip;
        this.user_name = user_name;
        this.password = password;
        this.email = email;
        this.status = status;
        this.is_deleted = is_deleted;
        this.created_by = created_by;
        this.created_date = created_date;
        this.qr_code = qr_code;
        this.session_token = session_token;
        this.apns_token = apns_token;
        this.img_url = img_url;
        this.company_name = company_name;
        this.site_ids = site_ids;
        this.designation = designation;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getCompany_id() {
        return company_id;
    }

    public void setCompany_id(String company_id) {
        this.company_id = company_id;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String getFather_name() {
        return father_name;
    }

    public void setFather_name(String father_name) {
        this.father_name = father_name;
    }

    public String getDob() {
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getL_address() {
        return l_address;
    }

    public void setL_address(String l_address) {
        this.l_address = l_address;
    }

    public String getP_address() {
        return p_address;
    }

    public void setP_address(String p_address) {
        this.p_address = p_address;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getIs_deleted() {
        return is_deleted;
    }

    public void setIs_deleted(String is_deleted) {
        this.is_deleted = is_deleted;
    }

    public String getCreated_by() {
        return created_by;
    }

    public void setCreated_by(String created_by) {
        this.created_by = created_by;
    }

    public java.util.Date getCreated_date() {
        return created_date;
    }

    public void setCreated_date(java.util.Date created_date) {
        this.created_date = created_date;
    }

    public String getQr_code() {
        return qr_code;
    }

    public void setQr_code(String qr_code) {
        this.qr_code = qr_code;
    }

    public String getSession_token() {
        return session_token;
    }

    public void setSession_token(String session_token) {
        this.session_token = session_token;
    }

    public String getApns_token() {
        return apns_token;
    }

    public void setApns_token(String apns_token) {
        this.apns_token = apns_token;
    }

    public String getImg_url() {
        return img_url;
    }

    public void setImg_url(String img_url) {
        this.img_url = img_url;
    }

    public String getCompany_name() {
        return company_name;
    }

    public void setCompany_name(String company_name) {
        this.company_name = company_name;
    }

    public String getSite_ids() {
        return site_ids;
    }

    public void setSite_ids(String site_ids) {
        this.site_ids = site_ids;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

}
