package com.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GUARD.
 */
public class Guard {

    private Long id;
    private String guard_id;
    private String company_id;
    private String first_name;
    private String last_name;
    private String phone;
    private String mobile;
    private String address;
    private String zip;
    private String post;
    private String technical_qualification;
    private String language_known;
    private String experience;
    private String passcode;
    private String pf_no;
    private String esi_no;
    private String status;
    private String is_deleted;
    private String created_by;
    private java.util.Date created_date;
    private String qr_code;
    private String site_id;
    private String companyName;
    private String user_id;
    private String siteVisitingId;
    private String img_url;
    private String designation;

    public Guard() {
    }

    public Guard(Long id) {
        this.id = id;
    }

    public Guard(Long id, String guard_id, String company_id, String first_name, String last_name, String phone, String mobile, String address, String zip, String post, String technical_qualification, String language_known, String experience, String passcode, String pf_no, String esi_no, String status, String is_deleted, String created_by, java.util.Date created_date, String qr_code, String site_id, String companyName, String user_id, String siteVisitingId, String img_url, String designation) {
        this.id = id;
        this.guard_id = guard_id;
        this.company_id = company_id;
        this.first_name = first_name;
        this.last_name = last_name;
        this.phone = phone;
        this.mobile = mobile;
        this.address = address;
        this.zip = zip;
        this.post = post;
        this.technical_qualification = technical_qualification;
        this.language_known = language_known;
        this.experience = experience;
        this.passcode = passcode;
        this.pf_no = pf_no;
        this.esi_no = esi_no;
        this.status = status;
        this.is_deleted = is_deleted;
        this.created_by = created_by;
        this.created_date = created_date;
        this.qr_code = qr_code;
        this.site_id = site_id;
        this.companyName = companyName;
        this.user_id = user_id;
        this.siteVisitingId = siteVisitingId;
        this.img_url = img_url;
        this.designation = designation;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGuard_id() {
        return guard_id;
    }

    public void setGuard_id(String guard_id) {
        this.guard_id = guard_id;
    }

    public String getCompany_id() {
        return company_id;
    }

    public void setCompany_id(String company_id) {
        this.company_id = company_id;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getPost() {
        return post;
    }

    public void setPost(String post) {
        this.post = post;
    }

    public String getTechnical_qualification() {
        return technical_qualification;
    }

    public void setTechnical_qualification(String technical_qualification) {
        this.technical_qualification = technical_qualification;
    }

    public String getLanguage_known() {
        return language_known;
    }

    public void setLanguage_known(String language_known) {
        this.language_known = language_known;
    }

    public String getExperience() {
        return experience;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

    public String getPasscode() {
        return passcode;
    }

    public void setPasscode(String passcode) {
        this.passcode = passcode;
    }

    public String getPf_no() {
        return pf_no;
    }

    public void setPf_no(String pf_no) {
        this.pf_no = pf_no;
    }

    public String getEsi_no() {
        return esi_no;
    }

    public void setEsi_no(String esi_no) {
        this.esi_no = esi_no;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getIs_deleted() {
        return is_deleted;
    }

    public void setIs_deleted(String is_deleted) {
        this.is_deleted = is_deleted;
    }

    public String getCreated_by() {
        return created_by;
    }

    public void setCreated_by(String created_by) {
        this.created_by = created_by;
    }

    public java.util.Date getCreated_date() {
        return created_date;
    }

    public void setCreated_date(java.util.Date created_date) {
        this.created_date = created_date;
    }

    public String getQr_code() {
        return qr_code;
    }

    public void setQr_code(String qr_code) {
        this.qr_code = qr_code;
    }

    public String getSite_id() {
        return site_id;
    }

    public void setSite_id(String site_id) {
        this.site_id = site_id;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getSiteVisitingId() {
        return siteVisitingId;
    }

    public void setSiteVisitingId(String siteVisitingId) {
        this.siteVisitingId = siteVisitingId;
    }

    public String getImg_url() {
        return img_url;
    }

    public void setImg_url(String img_url) {
        this.img_url = img_url;
    }

    public String getDesignation() {
        return designation;
    }

    public void setDesignation(String designation) {
        this.designation = designation;
    }

}
