package com.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGS_DATA.
 */
public class LogsData {

    private Long id;
    private String userId;
    private String parameters;
    private String isSynced;
    private java.util.Date dateAdded;

    public LogsData() {
    }

    public LogsData(Long id) {
        this.id = id;
    }

    public LogsData(Long id, String userId, String parameters, String isSynced, java.util.Date dateAdded) {
        this.id = id;
        this.userId = userId;
        this.parameters = parameters;
        this.isSynced = isSynced;
        this.dateAdded = dateAdded;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getParameters() {
        return parameters;
    }

    public void setParameters(String parameters) {
        this.parameters = parameters;
    }

    public String getIsSynced() {
        return isSynced;
    }

    public void setIsSynced(String isSynced) {
        this.isSynced = isSynced;
    }

    public java.util.Date getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(java.util.Date dateAdded) {
        this.dateAdded = dateAdded;
    }

}
