package com.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table QUESTIONS.
 */
public class Questions {

    private String question_id;
    private String question;
    private String company_id;
    private String is_mandatory;
    private String sequence;
    private String question_type;
    private String question_option;
    private String remark;
    private String is_published;
    private String answer;

    public Questions() {
    }

    public Questions(String question_id) {
        this.question_id = question_id;
    }

    public Questions(String question_id, String question, String company_id, String is_mandatory, String sequence, String question_type, String question_option, String remark, String is_published, String answer) {
        this.question_id = question_id;
        this.question = question;
        this.company_id = company_id;
        this.is_mandatory = is_mandatory;
        this.sequence = sequence;
        this.question_type = question_type;
        this.question_option = question_option;
        this.remark = remark;
        this.is_published = is_published;
        this.answer = answer;
    }

    public String getQuestion_id() {
        return question_id;
    }

    public void setQuestion_id(String question_id) {
        this.question_id = question_id;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getCompany_id() {
        return company_id;
    }

    public void setCompany_id(String company_id) {
        this.company_id = company_id;
    }

    public String getIs_mandatory() {
        return is_mandatory;
    }

    public void setIs_mandatory(String is_mandatory) {
        this.is_mandatory = is_mandatory;
    }

    public String getSequence() {
        return sequence;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public String getQuestion_type() {
        return question_type;
    }

    public void setQuestion_type(String question_type) {
        this.question_type = question_type;
    }

    public String getQuestion_option() {
        return question_option;
    }

    public void setQuestion_option(String question_option) {
        this.question_option = question_option;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getIs_published() {
        return is_published;
    }

    public void setIs_published(String is_published) {
        this.is_published = is_published;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

}
