package com.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SITE.
 */
public class Site {

    private String site_id;
    private String address;
    private String zipcode;
    private String city;
    private String emailId;
    private String contactPerson;
    private String contactNumber;
    private String branchId;
    private String branchName;
    private String customerName;
    private String companyName;
    private String user_id;
    private String siteVisitingId;

    public Site() {
    }

    public Site(String site_id) {
        this.site_id = site_id;
    }

    public Site(String site_id, String address, String zipcode, String city, String emailId, String contactPerson, String contactNumber, String branchId, String branchName, String customerName, String companyName, String user_id, String siteVisitingId) {
        this.site_id = site_id;
        this.address = address;
        this.zipcode = zipcode;
        this.city = city;
        this.emailId = emailId;
        this.contactPerson = contactPerson;
        this.contactNumber = contactNumber;
        this.branchId = branchId;
        this.branchName = branchName;
        this.customerName = customerName;
        this.companyName = companyName;
        this.user_id = user_id;
        this.siteVisitingId = siteVisitingId;
    }

    public String getSite_id() {
        return site_id;
    }

    public void setSite_id(String site_id) {
        this.site_id = site_id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getContactPerson() {
        return contactPerson;
    }

    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson;
    }

    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    public String getBranchId() {
        return branchId;
    }

    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    public String getBranchName() {
        return branchName;
    }

    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getSiteVisitingId() {
        return siteVisitingId;
    }

    public void setSiteVisitingId(String siteVisitingId) {
        this.siteVisitingId = siteVisitingId;
    }

}
