package com.android.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private String userId;
    private String emailId;
    private String status;
    private String companyId;
    private String name;
    private String roleId;
    private String roleName;
    private String code;
    private String regionId;
    private String branchId;
    private String siteId;
    private String userTasksIds;
    private String userTasks;
    private String sessionToken;

    public User() {
    }

    public User(String userId) {
        this.userId = userId;
    }

    public User(String userId, String emailId, String status, String companyId, String name, String roleId, String roleName, String code, String regionId, String branchId, String siteId, String userTasksIds, String userTasks, String sessionToken) {
        this.userId = userId;
        this.emailId = emailId;
        this.status = status;
        this.companyId = companyId;
        this.name = name;
        this.roleId = roleId;
        this.roleName = roleName;
        this.code = code;
        this.regionId = regionId;
        this.branchId = branchId;
        this.siteId = siteId;
        this.userTasksIds = userTasksIds;
        this.userTasks = userTasks;
        this.sessionToken = sessionToken;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getCompanyId() {
        return companyId;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRoleId() {
        return roleId;
    }

    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getRegionId() {
        return regionId;
    }

    public void setRegionId(String regionId) {
        this.regionId = regionId;
    }

    public String getBranchId() {
        return branchId;
    }

    public void setBranchId(String branchId) {
        this.branchId = branchId;
    }

    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public String getUserTasksIds() {
        return userTasksIds;
    }

    public void setUserTasksIds(String userTasksIds) {
        this.userTasksIds = userTasksIds;
    }

    public String getUserTasks() {
        return userTasks;
    }

    public void setUserTasks(String userTasks) {
        this.userTasks = userTasks;
    }

    public String getSessionToken() {
        return sessionToken;
    }

    public void setSessionToken(String sessionToken) {
        this.sessionToken = sessionToken;
    }

}
